name: api__3_1_0
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  vania: ^0.6.2
  mysql1: ^0.20.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.4

dependency_overrides:
  pointycastle: 3.7.3
